### PR TITLE
Pathing + Paths

### PR DESCRIPTION
**Pull request by SamboyCoding**
Adds generated paths and A* Pathing, and numerous other tweaks I can't remember off the top of my head.

### CODE REVIEW

**Comment by SamboyCoding** [comment]
Ouch. That's.. a lot of conflicts. Might have to force.

**Comment by TheTrueColonel** [comment]
This is going to be fun to resolve...

**Comment by SamboyCoding** [comment]
How the hell did I manage to change the damn Travis file

**Comment by FireController1847** [comment]
You didn't merge master correctly

**Comment by SamboyCoding** [comment]
I didn't merge master. I cherrypicked because I pulled after writing all the code like a dang fool.

**Comment by SamboyCoding** [comment]
Closing because I'm going to submit a non-screwed-up version.

**Pull request closed without merging**
