### PR TITLE
GitIgnore overhaul to cover every base

### PR DESCRIPTION
**Pull request by TheTrueColonel**

### CODE REVIEW

**Comment by FireController1847** [comment]
Mind giving a little more description in the issue?

**Comment by TheTrueColonel** [comment]
This allows anyone with any most any common use plugins for Eclipse, IntelliJ, Maven, Gradle, or Java to not have junk files being pushed into the repository. Keeps it clean.

**Comment by FireController1847** [comment]
This specific mod is mad using Eclipse, and I don't believe support tfor other platforms is something we're looking for. We appreciate the idea, though, and may consider it in the future. Pull requests welcome.

**Comment by TheTrueColonel** [comment]
Others, like I, may use IntelliJ, which is another IDE with a different structure to how files are handled. The plugins mentioned are different ways to build, diagnose, or help improve mod performance. They are completely user only, to help that user make mods/plugins. I feel without covering every base in an open source repository will cause a lot of issues down the line with unneeded files being added, and a lot of dirty .gitignore changes to mitigate those files. Might aswell stop it all now, instead of having the headache later.

**Comment by FireController1847** [comment]
We can handle these in pull requests or possible changes to the code later. I understand your concerns with the mod, but it has also caused issues with Eclipse being unable to launch correctly or understand files. The eclipse "junk files" are actually used to create a valid envitonment, and it's difficult to make a repository for both. For now, we plan on keeping it eclipse oriented, while in the future I may reopen this issue for further discussion.

**Comment by FireController1847** [comment]
Like I said, pull requests welcome.

**Comment by FireController1847** [comment]
I apologize for the confusion, an app on my phone was calling this an issue not a pull request. Reopened for further investgation.

**Comment by TheTrueColonel** [comment]
No problem. GitHub never had the best apps.

**Pull request merged**
