### PR TITLE
Documentation and a couple tweaks.

### PR DESCRIPTION
**Pull request by SamboyCoding**
Doesn't fix anything, but makes the code generally more readable by removing some methods, documenting a bunch of stuff, and just generally cleaning it up.

### CODE REVIEW

**Comment by SamboyCoding** [comment]
Oh, and also (hopefully) makes orientations other than east possible (although this isn't tested)

**Comment by SamboyCoding** [comment]
Ok, you gonna rebuild that travis?

**Comment by FireController1847** [comment]
Travis should rebuild on it's own for new commits.

**Comment by SamboyCoding** [comment]
There. Ready to merge.

**Pull request merged**
