### PR TITLE
TravisCI, CircleCI, README, and .gitignore

### PR DESCRIPTION
**Pull request by TheTrueColonel**
**Please describe the changes this PR makes and why it should be merged:**
.gitignore:
Ignored the entire .idea folder instead of individual .idea areas.

TravisCI, CircleCI, and README:
This part will require someone (most likely Boss) to have CircleCI (has a free plan), and TravisCI (also has a free plan), to be building the repo with every update.

The reason for the use of CIs and the use of the build badges (will need to be edited) is to prove reliability, and functionality in an Open Source project. CIs like TravisCI and CircleCI are used a lot with Open Source project, especially Minecraft related project, because of their ease of use, and badges showing that the plugin, mod, or addon will work and at least doesn't have any compilation errors.

### CODE REVIEW

**Comment by FireController1847** [comment]
I'll take a look at both free plan's on both Travis-CI and CircleCI, but this is my first time using them so bare with me.

**Comment by TheTrueColonel** [comment]
If you'd like some assistance, I can help.

**Comment by FireController1847** [comment]
Actually, would you mind giving me some steps to setting them up?

**Comment by FireController1847** [comment]
Thanks for this PR! \:)

**Pull request merged**
